name: 'run'

on:
  schedule:
    - cron: '30 0 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'setup python'
        uses: actions/setup-python@master
        with: 
          python-version: 3.7

      - name: requirements
        run : pip3 install requests

      - name: main
        env:
          cookie: ${{ secrets.cookie }}
        run: python3 ./HVSign.py
